version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q9b4t8y3
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t node-app .
      - docker tag node-app:latest public.ecr.aws/q9b4t8y3/node-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/q9b4t8y3/node-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"node-app","imageUri":"public.ecr.aws/q9b4t8y3/node-app:latest"}]' public.ecr.aws/q9b4t8y3/node-app:latest > imagedefinitions.json
artifacts:
    files:
        - imagedefinitions.json 
